title: Doc Smugglers
description: A test site for our Hackathon project.
theme: just-the-docs

url: https://somegraded.github.io

aux_links:
  The source: https://github.com/somegraded/somegraded.github.io

enable_copy_code_button: true